/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanhamentoContagemRouteImport } from './routes/acompanhamento-contagem'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as AnaliseCiclicaRouteImport } from './routes/analise-ciclica'
import { Route as AnaliseEstoqueRouteImport } from './routes/analise-estoque'
import { Route as AnaliseGestorRouteImport } from './routes/analise-gestor'
import { Route as AnaliseOficialRouteImport } from './routes/analise-oficial'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CicloRotativoRouteImport } from './routes/ciclo-rotativo'
import { Route as ConfiguracoesInventarioRouteImport } from './routes/configuracoes-inventario'
import { Route as ContagemRouteImport } from './routes/contagem'
import { Route as ControleInventariosRouteImport } from './routes/controle-inventarios'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapaEstoque3dRouteImport } from './routes/mapa-estoque-3d'
import { Route as OperadorRouteImport } from './routes/operador'
import { Route as RecontagemRouteImport } from './routes/recontagem'
import { Route as ResetSenhaRouteImport } from './routes/reset-senha'
import { Route as TratativasRouteImport } from './routes/tratativas'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as AcompanhamentoContagemLocalizacoesRouteImport } from './routes/acompanhamento-contagem_.localizacoes'
import { Route as InventariosIndexRouteImport } from './routes/inventarios.index'
import { Route as InventariosIdInventarioRouteImport } from './routes/inventarios.$idInventario'
import { Route as TratativasOcorrenciasRouteImport } from './routes/tratativas_.Ocorrencias'
import { Route as UsuariosIdUsuarioRouteImport } from './routes/usuarios_.$idUsuario'
import { Route as UsuariosNovoRouteImport } from './routes/usuarios_.novo'
import { Route as InventariosIdInventarioConfiguracaoRouteImport } from './routes/inventarios.$idInventario_.configuracao'
import { Route as InventariosIdInventarioControleRodadasRouteImport } from './routes/inventarios.$idInventario_.controle-rodadas'
import { Route as InventariosIdInventarioEstoqueEscopoRouteImport } from './routes/inventarios_.$idInventario.estoque-escopo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoContagemRoute = AcompanhamentoContagemRouteImport.update({
  id: '/acompanhamento-contagem',
  path: '/acompanhamento-contagem',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseCiclicaRoute = AnaliseCiclicaRouteImport.update({
  id: '/analise-ciclica',
  path: '/analise-ciclica',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseEstoqueRoute = AnaliseEstoqueRouteImport.update({
  id: '/analise-estoque',
  path: '/analise-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseGestorRoute = AnaliseGestorRouteImport.update({
  id: '/analise-gestor',
  path: '/analise-gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseOficialRoute = AnaliseOficialRouteImport.update({
  id: '/analise-oficial',
  path: '/analise-oficial',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CicloRotativoRoute = CicloRotativoRouteImport.update({
  id: '/ciclo-rotativo',
  path: '/ciclo-rotativo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesInventarioRoute = ConfiguracoesInventarioRouteImport.update({
  id: '/configuracoes-inventario',
  path: '/configuracoes-inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ContagemRoute = ContagemRouteImport.update({
  id: '/contagem',
  path: '/contagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleInventariosRoute = ControleInventariosRouteImport.update({
  id: '/controle-inventarios',
  path: '/controle-inventarios',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaEstoque3dRoute = MapaEstoque3dRouteImport.update({
  id: '/mapa-estoque-3d',
  path: '/mapa-estoque-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorRoute = OperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const RecontagemRoute = RecontagemRouteImport.update({
  id: '/recontagem',
  path: '/recontagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSenhaRoute = ResetSenhaRouteImport.update({
  id: '/reset-senha',
  path: '/reset-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TratativasRoute = TratativasRouteImport.update({
  id: '/tratativas',
  path: '/tratativas',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoContagemLocalizacoesRoute =
  AcompanhamentoContagemLocalizacoesRouteImport.update({
    id: '/acompanhamento-contagem_/localizacoes',
    path: '/acompanhamento-contagem/localizacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventariosIndexRoute = InventariosIndexRouteImport.update({
  id: '/inventarios/',
  path: '/inventarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventariosIdInventarioRoute = InventariosIdInventarioRouteImport.update({
  id: '/inventarios/$idInventario',
  path: '/inventarios/$idInventario',
  getParentRoute: () => rootRouteImport,
} as any)
const TratativasOcorrenciasRoute = TratativasOcorrenciasRouteImport.update({
  id: '/tratativas_/Ocorrencias',
  path: '/tratativas/Ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIdUsuarioRoute = UsuariosIdUsuarioRouteImport.update({
  id: '/usuarios_/$idUsuario',
  path: '/usuarios/$idUsuario',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosNovoRoute = UsuariosNovoRouteImport.update({
  id: '/usuarios_/novo',
  path: '/usuarios/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const InventariosIdInventarioConfiguracaoRoute =
  InventariosIdInventarioConfiguracaoRouteImport.update({
    id: '/inventarios/$idInventario_/configuracao',
    path: '/inventarios/$idInventario/configuracao',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventariosIdInventarioControleRodadasRoute =
  InventariosIdInventarioControleRodadasRouteImport.update({
    id: '/inventarios/$idInventario_/controle-rodadas',
    path: '/inventarios/$idInventario/controle-rodadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventariosIdInventarioEstoqueEscopoRoute =
  InventariosIdInventarioEstoqueEscopoRouteImport.update({
    id: '/inventarios_/$idInventario/estoque-escopo',
    path: '/inventarios/$idInventario/estoque-escopo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhamento-contagem': typeof AcompanhamentoContagemRoute
  '/analise': typeof AnaliseRoute
  '/analise-ciclica': typeof AnaliseCiclicaRoute
  '/analise-estoque': typeof AnaliseEstoqueRoute
  '/analise-gestor': typeof AnaliseGestorRoute
  '/analise-oficial': typeof AnaliseOficialRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastro': typeof CadastroRoute
  '/ciclo-rotativo': typeof CicloRotativoRoute
  '/configuracoes-inventario': typeof ConfiguracoesInventarioRoute
  '/contagem': typeof ContagemRoute
  '/controle-inventarios': typeof ControleInventariosRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/mapa-estoque-3d': typeof MapaEstoque3dRoute
  '/operador': typeof OperadorRoute
  '/recontagem': typeof RecontagemRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/tratativas': typeof TratativasRoute
  '/usuarios': typeof UsuariosRoute
  '/acompanhamento-contagem/localizacoes': typeof AcompanhamentoContagemLocalizacoesRoute
  '/inventarios/$idInventario': typeof InventariosIdInventarioRoute
  '/tratativas/Ocorrencias': typeof TratativasOcorrenciasRoute
  '/usuarios/$idUsuario': typeof UsuariosIdUsuarioRoute
  '/usuarios/novo': typeof UsuariosNovoRoute
  '/inventarios/': typeof InventariosIndexRoute
  '/inventarios/$idInventario/configuracao': typeof InventariosIdInventarioConfiguracaoRoute
  '/inventarios/$idInventario/controle-rodadas': typeof InventariosIdInventarioControleRodadasRoute
  '/inventarios/$idInventario/estoque-escopo': typeof InventariosIdInventarioEstoqueEscopoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhamento-contagem': typeof AcompanhamentoContagemRoute
  '/analise': typeof AnaliseRoute
  '/analise-ciclica': typeof AnaliseCiclicaRoute
  '/analise-estoque': typeof AnaliseEstoqueRoute
  '/analise-gestor': typeof AnaliseGestorRoute
  '/analise-oficial': typeof AnaliseOficialRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastro': typeof CadastroRoute
  '/ciclo-rotativo': typeof CicloRotativoRoute
  '/configuracoes-inventario': typeof ConfiguracoesInventarioRoute
  '/contagem': typeof ContagemRoute
  '/controle-inventarios': typeof ControleInventariosRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/mapa-estoque-3d': typeof MapaEstoque3dRoute
  '/operador': typeof OperadorRoute
  '/recontagem': typeof RecontagemRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/tratativas': typeof TratativasRoute
  '/usuarios': typeof UsuariosRoute
  '/acompanhamento-contagem/localizacoes': typeof AcompanhamentoContagemLocalizacoesRoute
  '/inventarios/$idInventario': typeof InventariosIdInventarioRoute
  '/tratativas/Ocorrencias': typeof TratativasOcorrenciasRoute
  '/usuarios/$idUsuario': typeof UsuariosIdUsuarioRoute
  '/usuarios/novo': typeof UsuariosNovoRoute
  '/inventarios': typeof InventariosIndexRoute
  '/inventarios/$idInventario/configuracao': typeof InventariosIdInventarioConfiguracaoRoute
  '/inventarios/$idInventario/controle-rodadas': typeof InventariosIdInventarioControleRodadasRoute
  '/inventarios/$idInventario/estoque-escopo': typeof InventariosIdInventarioEstoqueEscopoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhamento-contagem': typeof AcompanhamentoContagemRoute
  '/analise': typeof AnaliseRoute
  '/analise-ciclica': typeof AnaliseCiclicaRoute
  '/analise-estoque': typeof AnaliseEstoqueRoute
  '/analise-gestor': typeof AnaliseGestorRoute
  '/analise-oficial': typeof AnaliseOficialRoute
  '/auditoria': typeof AuditoriaRoute
  '/cadastro': typeof CadastroRoute
  '/ciclo-rotativo': typeof CicloRotativoRoute
  '/configuracoes-inventario': typeof ConfiguracoesInventarioRoute
  '/contagem': typeof ContagemRoute
  '/controle-inventarios': typeof ControleInventariosRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/mapa-estoque-3d': typeof MapaEstoque3dRoute
  '/operador': typeof OperadorRoute
  '/recontagem': typeof RecontagemRoute
  '/reset-senha': typeof ResetSenhaRoute
  '/tratativas': typeof TratativasRoute
  '/usuarios': typeof UsuariosRoute
  '/acompanhamento-contagem_/localizacoes': typeof AcompanhamentoContagemLocalizacoesRoute
  '/inventarios/$idInventario': typeof InventariosIdInventarioRoute
  '/tratativas_/Ocorrencias': typeof TratativasOcorrenciasRoute
  '/usuarios_/$idUsuario': typeof UsuariosIdUsuarioRoute
  '/usuarios_/novo': typeof UsuariosNovoRoute
  '/inventarios/': typeof InventariosIndexRoute
  '/inventarios/$idInventario_/configuracao': typeof InventariosIdInventarioConfiguracaoRoute
  '/inventarios/$idInventario_/controle-rodadas': typeof InventariosIdInventarioControleRodadasRoute
  '/inventarios_/$idInventario/estoque-escopo': typeof InventariosIdInventarioEstoqueEscopoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhamento-contagem'
    | '/analise'
    | '/analise-ciclica'
    | '/analise-estoque'
    | '/analise-gestor'
    | '/analise-oficial'
    | '/auditoria'
    | '/cadastro'
    | '/ciclo-rotativo'
    | '/configuracoes-inventario'
    | '/contagem'
    | '/controle-inventarios'
    | '/esqueci-senha'
    | '/historico'
    | '/indicadores'
    | '/login'
    | '/mapa-estoque-3d'
    | '/operador'
    | '/recontagem'
    | '/reset-senha'
    | '/tratativas'
    | '/usuarios'
    | '/acompanhamento-contagem/localizacoes'
    | '/inventarios/$idInventario'
    | '/tratativas/Ocorrencias'
    | '/usuarios/$idUsuario'
    | '/usuarios/novo'
    | '/inventarios/'
    | '/inventarios/$idInventario/configuracao'
    | '/inventarios/$idInventario/controle-rodadas'
    | '/inventarios/$idInventario/estoque-escopo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhamento-contagem'
    | '/analise'
    | '/analise-ciclica'
    | '/analise-estoque'
    | '/analise-gestor'
    | '/analise-oficial'
    | '/auditoria'
    | '/cadastro'
    | '/ciclo-rotativo'
    | '/configuracoes-inventario'
    | '/contagem'
    | '/controle-inventarios'
    | '/esqueci-senha'
    | '/historico'
    | '/indicadores'
    | '/login'
    | '/mapa-estoque-3d'
    | '/operador'
    | '/recontagem'
    | '/reset-senha'
    | '/tratativas'
    | '/usuarios'
    | '/acompanhamento-contagem/localizacoes'
    | '/inventarios/$idInventario'
    | '/tratativas/Ocorrencias'
    | '/usuarios/$idUsuario'
    | '/usuarios/novo'
    | '/inventarios'
    | '/inventarios/$idInventario/configuracao'
    | '/inventarios/$idInventario/controle-rodadas'
    | '/inventarios/$idInventario/estoque-escopo'
  id:
    | '__root__'
    | '/'
    | '/acompanhamento-contagem'
    | '/analise'
    | '/analise-ciclica'
    | '/analise-estoque'
    | '/analise-gestor'
    | '/analise-oficial'
    | '/auditoria'
    | '/cadastro'
    | '/ciclo-rotativo'
    | '/configuracoes-inventario'
    | '/contagem'
    | '/controle-inventarios'
    | '/esqueci-senha'
    | '/historico'
    | '/indicadores'
    | '/login'
    | '/mapa-estoque-3d'
    | '/operador'
    | '/recontagem'
    | '/reset-senha'
    | '/tratativas'
    | '/usuarios'
    | '/acompanhamento-contagem_/localizacoes'
    | '/inventarios/$idInventario'
    | '/tratativas_/Ocorrencias'
    | '/usuarios_/$idUsuario'
    | '/usuarios_/novo'
    | '/inventarios/'
    | '/inventarios/$idInventario_/configuracao'
    | '/inventarios/$idInventario_/controle-rodadas'
    | '/inventarios_/$idInventario/estoque-escopo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanhamentoContagemRoute: typeof AcompanhamentoContagemRoute
  AnaliseRoute: typeof AnaliseRoute
  AnaliseCiclicaRoute: typeof AnaliseCiclicaRoute
  AnaliseEstoqueRoute: typeof AnaliseEstoqueRoute
  AnaliseGestorRoute: typeof AnaliseGestorRoute
  AnaliseOficialRoute: typeof AnaliseOficialRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CadastroRoute: typeof CadastroRoute
  CicloRotativoRoute: typeof CicloRotativoRoute
  ConfiguracoesInventarioRoute: typeof ConfiguracoesInventarioRoute
  ContagemRoute: typeof ContagemRoute
  ControleInventariosRoute: typeof ControleInventariosRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  HistoricoRoute: typeof HistoricoRoute
  IndicadoresRoute: typeof IndicadoresRoute
  LoginRoute: typeof LoginRoute
  MapaEstoque3dRoute: typeof MapaEstoque3dRoute
  OperadorRoute: typeof OperadorRoute
  RecontagemRoute: typeof RecontagemRoute
  ResetSenhaRoute: typeof ResetSenhaRoute
  TratativasRoute: typeof TratativasRoute
  UsuariosRoute: typeof UsuariosRoute
  AcompanhamentoContagemLocalizacoesRoute: typeof AcompanhamentoContagemLocalizacoesRoute
  InventariosIdInventarioRoute: typeof InventariosIdInventarioRoute
  TratativasOcorrenciasRoute: typeof TratativasOcorrenciasRoute
  UsuariosIdUsuarioRoute: typeof UsuariosIdUsuarioRoute
  UsuariosNovoRoute: typeof UsuariosNovoRoute
  InventariosIndexRoute: typeof InventariosIndexRoute
  InventariosIdInventarioConfiguracaoRoute: typeof InventariosIdInventarioConfiguracaoRoute
  InventariosIdInventarioControleRodadasRoute: typeof InventariosIdInventarioControleRodadasRoute
  InventariosIdInventarioEstoqueEscopoRoute: typeof InventariosIdInventarioEstoqueEscopoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento-contagem': {
      id: '/acompanhamento-contagem'
      path: '/acompanhamento-contagem'
      fullPath: '/acompanhamento-contagem'
      preLoaderRoute: typeof AcompanhamentoContagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-ciclica': {
      id: '/analise-ciclica'
      path: '/analise-ciclica'
      fullPath: '/analise-ciclica'
      preLoaderRoute: typeof AnaliseCiclicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-estoque': {
      id: '/analise-estoque'
      path: '/analise-estoque'
      fullPath: '/analise-estoque'
      preLoaderRoute: typeof AnaliseEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-gestor': {
      id: '/analise-gestor'
      path: '/analise-gestor'
      fullPath: '/analise-gestor'
      preLoaderRoute: typeof AnaliseGestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-oficial': {
      id: '/analise-oficial'
      path: '/analise-oficial'
      fullPath: '/analise-oficial'
      preLoaderRoute: typeof AnaliseOficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciclo-rotativo': {
      id: '/ciclo-rotativo'
      path: '/ciclo-rotativo'
      fullPath: '/ciclo-rotativo'
      preLoaderRoute: typeof CicloRotativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes-inventario': {
      id: '/configuracoes-inventario'
      path: '/configuracoes-inventario'
      fullPath: '/configuracoes-inventario'
      preLoaderRoute: typeof ConfiguracoesInventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contagem': {
      id: '/contagem'
      path: '/contagem'
      fullPath: '/contagem'
      preLoaderRoute: typeof ContagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle-inventarios': {
      id: '/controle-inventarios'
      path: '/controle-inventarios'
      fullPath: '/controle-inventarios'
      preLoaderRoute: typeof ControleInventariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-estoque-3d': {
      id: '/mapa-estoque-3d'
      path: '/mapa-estoque-3d'
      fullPath: '/mapa-estoque-3d'
      preLoaderRoute: typeof MapaEstoque3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador': {
      id: '/operador'
      path: '/operador'
      fullPath: '/operador'
      preLoaderRoute: typeof OperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recontagem': {
      id: '/recontagem'
      path: '/recontagem'
      fullPath: '/recontagem'
      preLoaderRoute: typeof RecontagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-senha': {
      id: '/reset-senha'
      path: '/reset-senha'
      fullPath: '/reset-senha'
      preLoaderRoute: typeof ResetSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratativas': {
      id: '/tratativas'
      path: '/tratativas'
      fullPath: '/tratativas'
      preLoaderRoute: typeof TratativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento-contagem_/localizacoes': {
      id: '/acompanhamento-contagem_/localizacoes'
      path: '/acompanhamento-contagem/localizacoes'
      fullPath: '/acompanhamento-contagem/localizacoes'
      preLoaderRoute: typeof AcompanhamentoContagemLocalizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventarios/': {
      id: '/inventarios/'
      path: '/inventarios'
      fullPath: '/inventarios/'
      preLoaderRoute: typeof InventariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventarios/$idInventario': {
      id: '/inventarios/$idInventario'
      path: '/inventarios/$idInventario'
      fullPath: '/inventarios/$idInventario'
      preLoaderRoute: typeof InventariosIdInventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratativas_/Ocorrencias': {
      id: '/tratativas_/Ocorrencias'
      path: '/tratativas/Ocorrencias'
      fullPath: '/tratativas/Ocorrencias'
      preLoaderRoute: typeof TratativasOcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios_/$idUsuario': {
      id: '/usuarios_/$idUsuario'
      path: '/usuarios/$idUsuario'
      fullPath: '/usuarios/$idUsuario'
      preLoaderRoute: typeof UsuariosIdUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios_/novo': {
      id: '/usuarios_/novo'
      path: '/usuarios/novo'
      fullPath: '/usuarios/novo'
      preLoaderRoute: typeof UsuariosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventarios/$idInventario_/configuracao': {
      id: '/inventarios/$idInventario_/configuracao'
      path: '/inventarios/$idInventario/configuracao'
      fullPath: '/inventarios/$idInventario/configuracao'
      preLoaderRoute: typeof InventariosIdInventarioConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventarios/$idInventario_/controle-rodadas': {
      id: '/inventarios/$idInventario_/controle-rodadas'
      path: '/inventarios/$idInventario/controle-rodadas'
      fullPath: '/inventarios/$idInventario/controle-rodadas'
      preLoaderRoute: typeof InventariosIdInventarioControleRodadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventarios_/$idInventario/estoque-escopo': {
      id: '/inventarios_/$idInventario/estoque-escopo'
      path: '/inventarios/$idInventario/estoque-escopo'
      fullPath: '/inventarios/$idInventario/estoque-escopo'
      preLoaderRoute: typeof InventariosIdInventarioEstoqueEscopoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanhamentoContagemRoute: AcompanhamentoContagemRoute,
  AnaliseRoute: AnaliseRoute,
  AnaliseCiclicaRoute: AnaliseCiclicaRoute,
  AnaliseEstoqueRoute: AnaliseEstoqueRoute,
  AnaliseGestorRoute: AnaliseGestorRoute,
  AnaliseOficialRoute: AnaliseOficialRoute,
  AuditoriaRoute: AuditoriaRoute,
  CadastroRoute: CadastroRoute,
  CicloRotativoRoute: CicloRotativoRoute,
  ConfiguracoesInventarioRoute: ConfiguracoesInventarioRoute,
  ContagemRoute: ContagemRoute,
  ControleInventariosRoute: ControleInventariosRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  HistoricoRoute: HistoricoRoute,
  IndicadoresRoute: IndicadoresRoute,
  LoginRoute: LoginRoute,
  MapaEstoque3dRoute: MapaEstoque3dRoute,
  OperadorRoute: OperadorRoute,
  RecontagemRoute: RecontagemRoute,
  ResetSenhaRoute: ResetSenhaRoute,
  TratativasRoute: TratativasRoute,
  UsuariosRoute: UsuariosRoute,
  AcompanhamentoContagemLocalizacoesRoute:
    AcompanhamentoContagemLocalizacoesRoute,
  InventariosIdInventarioRoute: InventariosIdInventarioRoute,
  TratativasOcorrenciasRoute: TratativasOcorrenciasRoute,
  UsuariosIdUsuarioRoute: UsuariosIdUsuarioRoute,
  UsuariosNovoRoute: UsuariosNovoRoute,
  InventariosIndexRoute: InventariosIndexRoute,
  InventariosIdInventarioConfiguracaoRoute:
    InventariosIdInventarioConfiguracaoRoute,
  InventariosIdInventarioControleRodadasRoute:
    InventariosIdInventarioControleRodadasRoute,
  InventariosIdInventarioEstoqueEscopoRoute:
    InventariosIdInventarioEstoqueEscopoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
